### ISSUE TITLE
Making processor incremental 

### ISSUE THREAD

**Issue by MFlisar** [fabioCollini/Inversion#1]
May this be possible? Can it eventually even be marked as an isolated annotation processor? Incremental builds are not yet supported, are they?

You can find more about what I'm talking about here, if you don't know it yet already: https://docs.gradle.org/nightly/userguide/java_plugin.html#sec:incremental_annotation_processing

**Comment by fabioCollini** [comment]
You are right, the current version doesn't support incremental builds :(

I'll work on it soon, I am not sure if everything (both the code generation and the check that an implementation exists) can be done using an incremental annotation processor

**Comment by fabioCollini** [comment]
I have worked on it and released a new version, using 0.3.1 the annotation processor is incremental. Unfortunately it's not possible to validate everything at compile time, so the re is a new `Inversion.validate()` that can be invoked in a test or when the application starts.
